version: "3.7"

services:
  monitoring_app:
    container_name: monitoring_app
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: run
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    env_file: .env
    ports:
      - 127.0.0.1:8000:8000
volumes:
  unaa-data: