version: "3.8"

services:
  app:
    container_name: monitoring_app
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: run
    volumes:
      - ./media:/app/media
      - /opt/backend/static:/app/backend/static
    env_file: .env.example
    ports:
      - 127.0.0.1:8000:8000
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  db:
    container_name: db
    restart: always
    image: postgres:12.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file: .env.example
    expose:
      - 5432

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    expose:
      - 6379

volumes:
  postgres-data:
  static:
