# Generated by Django 4.2.7 on 2023-11-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rtsp_url', models.URLField()),
                ('last_status', models.BooleanField(null=True)),
                ('last_connected_at', models.DateTimeField(null=True)),
                ('last_disconnected_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
