# Generated by Django 4.2.7 on 2023-11-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_rename_rtsp_url_camera_raw_rtsp_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rtsp_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StreamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cameras.stream')),
            ],
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
