# Generated by Django 4.2.7 on 2023-11-30 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_stream_streamstatus_delete_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Stream',
            new_name='Camera',
        ),
        migrations.DeleteModel(
            name='StreamStatus',
        ),
        migrations.AddField(
            model_name='camerastatus',
            name='camera',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cameras.camera'),
        ),
    ]
