# Generated by Django 4.2.7 on 2023-11-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_camerastatus_rename_stream_camera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='rtsp_url',
        ),
        migrations.AddField(
            model_name='camera',
            name='url',
            field=models.URLField(default=3434),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CameraStatus',
        ),
    ]
