# Generated by Django 4.2.7 on 2023-12-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_remove_camera_rtsp_url_camera_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Добавить', 'verbose_name_plural': 'Добавить камеру'},
        ),
        migrations.AlterField(
            model_name='camera',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название камеры'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.URLField(verbose_name='Вставьте ссылку'),
        ),
    ]
