# Generated by Django 4.2.7 on 2023-12-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_alter_camera_options_alter_camera_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название камеры'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.URLField(db_index=True, verbose_name='Вставьте ссылку'),
        ),
    ]
